### PR TITLE
Plot arithmetic

### LINKED ISSUE #96: Plot arithmetic for ggsurvfit?
Is it feasible to export methods for `+.ggsurvfit`, `-.ggsurvfit`, `/.ggsurvfit`, etc. They would work just like the patchwork versions, but would call `ggsurvfit_build()` to first construct the risktable, then pass the objects on to the ggplot2 methods.

https://patchwork.data-imaginist.com/reference/plot_arithmetic.html

I did some preliminary testing with a built ggsurvfit figure, and it did not seem to be as straight-forward as I was hoping.

### PR DESCRIPTION
**Pull request by ddsjoberg**
**What changes are proposed in this pull request?**
* Added patchwork-like arithmetic operators for combining ggsurvit figures: `|`, `-`, and `\`.

Caveats:
- I couldn't figure out how to implement the `+` operator.
- I didn't implement `*` and `&` because I am not really sure what they are for!
- Because there is not 100% consistency with the patchwork operators, is it even work adding these to the pkg? I think so, because it makes it much easier to place plots side by side (no need to build the figure before placing side by side).
- User _can_ use the patchwork operators directly, but the ggsurvfit object must first be built, then wrapped in `wrap_elements()`. But that is pretty confusing to most users I would imagine.

image

**If there is an GitHub issue associated with this pull request, please provide link.**
closes #96

--------------------------------------------------------------------------------

Reviewer Checklist (if item does not apply, mark is as complete)

- [ ] Ensure all package dependencies are installed by running `renv::install()`
- [ ] PR branch has pulled the most recent updates from master branch. Ensure the pull request branch and your local version match and both have the latest updates from the master branch.
- [ ] If a new function was added, function included in `_pkgdown.yml`
- [ ] If a bug was fixed, a unit test was added for the bug check
- [ ] Run `pkgdown::build_site()`. Check the R console for errors, and review the rendered website.
- [ ] Overall code coverage remains >99.5%. Review coverage with `withr::with_envvar(new = c("NOT_CRAN" = "true"), covr::report())`. Begin in a fresh R session without any packages loaded. 
- [ ] R CMD Check runs without errors, warnings, and notes
- [ ] `usethis::use_spell_check()` runs with no spelling errors in documentation

When the branch is ready to be merged into master:
- [ ] Update `NEWS.md` with the changes from this pull request under the heading "`# ggsurvfit (development version)`". If there is an issue associated with the pull request, reference it in parentheses at the end update (see `NEWS.md` for examples).
- [ ] Increment the version number using `usethis::use_version(which = "dev")` 
- [ ] Run `codemetar::write_codemeta()`
- [ ] Run `usethis::use_spell_check()` again
- [ ] Approve Pull Request
- [ ] Merge the PR. Please use "Squash and merge".

### CODE REVIEW

**Comment by michaelcurry1123** [comment]
The horizontal stack makes numbers in risk tables overlap.

p1 <- survfit2(Surv(time, status) ~ sex, data = df_lung) %>%
  ggsurvfit() +
  add_risktable()


p2 <- survfit2(Surv(time, status) ~ sex, data = df_lung) %>%
  ggsurvfit() +
  add_risktable()

p1/p2

image

**Comment by ddsjoberg** [comment]
Thanks for taking a look @michaelcurry1123 !

Regarding the first point: The issue is that after `p1 | p2` is run, the result is no longer a ggsurvfit object (it's a regular patched together plot at that point. So when that result is then dispatched to `. | p3`, we're no longer using the `|.ggsurvfit` method and it's being dispatched via the patchwork method and it doesn't know how to handle the ggsurvfit plot.

Potential solutions:
1. Making the documentation more clear about this issue.
2. We could attempt to export conflicting method for ggplot class (it would mask the patchwork method or vice versa) so we can explicitly handle the second argument when it is class ggsurvfit.

I think for now, we'll need to opt for option one...I don't like the idea of exporting a conflicting method with patchwork AND I think it will be tricky to export this method while also trying to utilize the patchwork method in the background: there will be conflict.

Regarding the second point: That is just the default spacing. If you make the figure taller, the plots and risk tables will display appropriately

**Comment by michaelcurry1123** [comment]
Ok that makes sense and if someone wants that customization you can do it like so:

```
library(gridExtra)

grid.arrange(p1,p2,p3,
             layout_matrix = 
              matrix(
                c(1,1,1,2,2,2,
                1,1,1,2,2,2,
                1,1,1,2,2,2,
                1,1,1,2,2,2,
                3,3,3,3,3,3,
                3,3,3,3,3,3),
               byrow = TRUE, ncol = 6)
            )
```

**Comment by ddsjoberg** [comment]
Let's hold off on this until the next release for this. I would hope to get `p | p | p` working properly if at all possible.

1. Can we properly implement a `|.ggplot` method that could build and wrap the second argument as needed, then pass that object to the patchwork implementation of `|.ggplot` ?
2. The issue here is trying to work with 2 different `|.ggplot` methods. If we did more reading perhaps we could implement our own `|.ggplot` methods, but pass those on to `patchwork::wrap_plots()` instead of taking advantage of the patchwork arithmetic operators. I am not sure if this would interact with the other functions that work with the operators exported from patchwork.

Oy!

**Comment by michaelcurry1123** [comment]
complex issue! happy to help think through this with you for next release.

**Comment by ddsjoberg** [comment]
\document

**Comment by ddsjoberg** [comment]
closing in favor of S7

**Pull request closed without merging**
